/**
 * Requests generated from an API description, in the forms other tools take: a Postman
 * collection (format v2.1), a `.http` file (the VS Code REST Client extension and the JetBrains
 * HTTP client both read it) and a curl command. Nothing here knows where a description came
 * from: the Explorer builds requests from the SysAdmin OpenAPI document
 * (`features/explorer/requests.ts`), REST services from the Swagger 2.0 that `/api/mgmnt`
 * generates for a dispatch class (`api/mgmnt.ts`, `routeRequests`).
 *
 * The password never leaves the browser: a collection authenticates with `{{username}}` and an
 * empty `{{password}}` variable, a `.http` file with an `@password` to fill in, and curl with
 * `-u user`, which asks for it. Body values under a secret key are redacted by the callers
 * (`lib/redact.ts`) before they get here.
 *
 * This is what Ideas Portal idea DPI-I-813 asks for (requests derived from the OpenAPI
 * description instead of typed field by field, importable into Postman), done for the portal.
 */

export interface RequestParam {
  name: string;
  /** What to send; empty when the description gives no example and nothing was typed. */
  value: string;
  required: boolean;
  description?: string;
  type?: string;
}

export interface GeneratedRequest {
  /** Its label in a collection or file: "GET /v2/namespaces". */
  name: string;
  method: string;
  /** Absolute on the instance (/api/admin/v2/namespaces); `{name}` marks a path parameter. */
  path: string;
  summary?: string;
  /** Context lines: privileges, whether the answer is a 202, what to replace in the path. */
  notes?: string[];
  query: RequestParam[];
  /** JSON, already serialised, or nothing. */
  body?: string;
  /** The folder of a collection, and a comment line of a file section. */
  folder?: string;
}

export interface ExportTarget {
  /** Where the instance answers: scheme, host and any path prefix, no trailing slash. */
  baseUrl: string;
  username: string;
  /** The collection's or file's name. */
  name: string;
  description?: string;
  /** Where the requests come from, for the header comment. */
  source?: string;
  /** The date written into the header; today when absent. */
  date?: string;
}

export const POSTMAN_SCHEMA = 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json';

export interface PostmanItem {
  name: string;
  request: {
    method: string;
    header: { key: string; value: string }[];
    url: {
      raw: string;
      host: string[];
      path: string[];
      query?: { key: string; value: string; description?: string; disabled?: boolean }[];
      variable?: { key: string; value: string }[];
    };
    description?: string;
    body?: { mode: 'raw'; raw: string; options: { raw: { language: 'json' } } };
  };
  response: never[];
}

export interface PostmanCollection {
  info: { name: string; description: string; schema: string };
  auth: { type: 'basic'; basic: { key: string; value: string; type: 'string' }[] };
  variable: { key: string; value: string; type?: 'secret' }[];
  item: ({ name: string; item: PostmanItem[] } | PostmanItem)[];
}

const PATH_PARAM = /\{([^}/]+)\}/g;

/** The `{name}` parameters of a path template, in order. */
export function pathParamsOf(path: string): string[] {
  return [...path.matchAll(PATH_PARAM)].map((m) => m[1]);
}

/**
 * The base URL a connection profile names, made absolute: '' and '/prefix' are the page's own
 * origin (the nginx and IRIS-hosted deployments), anything with a scheme stays as it is.
 */
export function absoluteBaseUrl(
  baseUrl: string,
  origin = typeof location === 'undefined' ? '' : location.origin,
): string {
  const text = baseUrl.trim().replace(/\/+$/, '');
  if (/^https?:\/\//i.test(text)) return text;
  return `${origin}${text && !text.startsWith('/') ? `/${text}` : text}`;
}

/** A name safe for a file: "/api/atelier" → "api-atelier". */
export function fileStem(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'requests'
  );
}

/** The query parameters a request sends: the ones with a value, and the required ones (to fill in). */
function sent(r: GeneratedRequest): RequestParam[] {
  return r.query.filter((p) => p.value !== '' || p.required);
}

/** The optional parameters left out, so a comment can name them. */
function omitted(r: GeneratedRequest): string[] {
  return r.query.filter((p) => p.value === '' && !p.required).map((p) => p.name);
}

function queryString(params: RequestParam[], encode: (s: string) => string): string {
  return params.length ? `?${params.map((p) => `${encode(p.name)}=${encode(p.value)}`).join('&')}` : '';
}

function generatedBy(target: ExportTarget): string {
  const date = target.date ?? new Date().toISOString().slice(0, 10);
  return `Generated by Aperture on ${date}${target.source ? ` from ${target.source}` : ''}.`;
}

function itemDescription(r: GeneratedRequest): string {
  return [r.summary, ...(r.notes ?? [])].filter(Boolean).join('\n');
}

function postmanItem(r: GeneratedRequest): PostmanItem {
  // Postman's own OpenAPI importer writes path parameters as `:name` with a variable each.
  const path = r.path
    .replace(/^\/+/, '')
    .split('/')
    .map((s) => s.replace(/^\{([^}]+)\}$/, ':$1'));
  const variables = pathParamsOf(r.path);
  const query = r.query.map((p) => ({
    key: p.name,
    value: p.value,
    ...(p.description ? { description: p.description } : {}),
    ...(p.value === '' && !p.required ? { disabled: true } : {}),
  }));
  const description = itemDescription(r);
  return {
    name: r.name,
    request: {
      method: r.method,
      header: [
        { key: 'Accept', value: 'application/json' },
        ...(r.body !== undefined ? [{ key: 'Content-Type', value: 'application/json' }] : []),
      ],
      url: {
        raw: `{{baseUrl}}/${path.join('/')}${queryString(sent(r), (s) => s)}`,
        host: ['{{baseUrl}}'],
        path,
        ...(query.length ? { query } : {}),
        ...(variables.length ? { variable: variables.map((key) => ({ key, value: '' })) } : {}),
      },
      ...(description ? { description } : {}),
      ...(r.body !== undefined
        ? { body: { mode: 'raw' as const, raw: r.body, options: { raw: { language: 'json' as const } } } }
        : {}),
    },
    response: [],
  };
}

/** A Postman collection (format v2.1), one folder per `folder`, Basic auth from two variables. */
export function postmanCollection(target: ExportTarget, requests: GeneratedRequest[]): PostmanCollection {
  const folders = new Map<string, PostmanItem[]>();
  const loose: PostmanItem[] = [];
  for (const r of requests) {
    const item = postmanItem(r);
    if (r.folder) (folders.get(r.folder) ?? folders.set(r.folder, []).get(r.folder)!).push(item);
    else loose.push(item);
  }
  return {
    info: {
      name: target.name,
      description: [target.description, generatedBy(target)].filter(Boolean).join('\n\n'),
      schema: POSTMAN_SCHEMA,
    },
    auth: {
      type: 'basic',
      basic: [
        { key: 'username', value: '{{username}}', type: 'string' },
        { key: 'password', value: '{{password}}', type: 'string' },
      ],
    },
    variable: [
      { key: 'baseUrl', value: target.baseUrl },
      { key: 'username', value: target.username },
      { key: 'password', value: '', type: 'secret' },
    ],
    item: [...[...folders].map(([name, item]) => ({ name, item })), ...loose],
  };
}

/**
 * A `.http` file: one `###` block per request, file variables for the instance and the account.
 * The VS Code REST Client extension and the JetBrains HTTP client both take
 * `Authorization: Basic {{username}} {{password}}` and encode it.
 */
export function httpFile(target: ExportTarget, requests: GeneratedRequest[]): string {
  const out = [`# ${target.name}`];
  if (target.description) out.push(`# ${target.description}`);
  out.push(
    `# ${generatedBy(target)}`,
    '# Opens in VS Code (REST Client extension) and in JetBrains IDEs. Set @password before sending,',
    '# and keep the file out of version control once it holds one.',
    `@baseUrl = ${target.baseUrl}`,
    `@username = ${target.username}`,
    '@password =',
  );
  for (const r of requests) {
    out.push('', `### ${r.name}${r.summary ? ` · ${r.summary}` : ''}`);
    for (const line of [...(r.folder ? [r.folder] : []), ...(r.notes ?? [])]) out.push(`# ${line}`);
    const left = omitted(r);
    if (left.length) out.push(`# Optional query parameters left out: ${left.join(', ')}`);
    out.push(
      `${r.method} {{baseUrl}}${r.path}${queryString(sent(r), encodeURIComponent)} HTTP/1.1`,
      'Accept: application/json',
    );
    if (r.body !== undefined) out.push('Content-Type: application/json');
    out.push('Authorization: Basic {{username}} {{password}}');
    if (r.body !== undefined) out.push('', r.body);
  }
  return `${out.join('\n')}\n`;
}

const quote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;

/** Where the curl commands run as they are: the single quotes are for POSIX shells. */
export const CURL_SHELL_NOTE =
  'Quoted for bash and zsh (macOS, Linux, WSL, Git Bash); in cmd.exe or Windows PowerShell, run it from Git Bash or WSL.';

/** One curl command; `-u user` without a password makes curl ask for it. */
export function curlCommand(target: Pick<ExportTarget, 'baseUrl' | 'username'>, r: GeneratedRequest): string {
  const parts = [`curl -u ${quote(target.username)}`, `-H 'Accept: application/json'`];
  if (r.method !== 'GET') parts.push(`-X ${r.method}`);
  if (r.body !== undefined)
    parts.push(`-H 'Content-Type: application/json'`, `--data-binary ${quote(r.body)}`);
  parts.push(quote(`${target.baseUrl}${r.path}${queryString(sent(r), encodeURIComponent)}`));
  return parts.join(' \\\n  ');
}
