import { describe, expect, it } from 'vitest';
import {
  absoluteBaseUrl,
  curlCommand,
  fileStem,
  httpFile,
  pathParamsOf,
  postmanCollection,
  POSTMAN_SCHEMA,
  type ExportTarget,
  type GeneratedRequest,
} from '../requestExport';

const target: ExportTarget = {
  baseUrl: 'http://iris.test:52773',
  username: '_SYSTEM',
  name: 'SysAdmin API',
  description: 'Every operation',
  source: 'spec/mainspec_v2.json',
  date: '2026-09-25',
};

const list: GeneratedRequest = {
  name: 'GET /v2/namespaces',
  method: 'GET',
  path: '/api/admin/v2/namespaces',
  summary: 'List namespaces',
  notes: ['Needs %Admin_Manage:U'],
  query: [{ name: 'filter', value: '', required: false, description: 'A name filter' }],
  folder: 'Namespaces',
};

const compact: GeneratedRequest = {
  name: 'POST /v2/database-dir/compact',
  method: 'POST',
  path: '/api/admin/v2/database-dir/compact',
  summary: 'Compact a local database',
  notes: ['Needs %Admin_Operate:U', 'Answers 202 Accepted'],
  query: [
    { name: 'dir', value: '/usr/irissys/mgr/user/', required: true },
    { name: 'verbose', value: 'true', required: false },
  ],
  body: '{\n  "TargetFreeSpace": 0\n}',
  folder: 'Local databases',
};

const doc: GeneratedRequest = {
  name: 'GET /v1/{namespace}/doc/{docname}',
  method: 'GET',
  path: '/api/atelier/v1/{namespace}/doc/{docname}',
  query: [],
};

describe('requests for other tools', () => {
  it('writes a Postman collection with folders, variables and Basic auth from variables', () => {
    const c = postmanCollection(target, [list, compact, doc]);
    expect(c.info.schema).toBe(POSTMAN_SCHEMA);
    expect(c.info.description).toContain('Generated by Aperture on 2026-09-25 from spec/mainspec_v2.json.');
    expect(c.variable).toEqual([
      { key: 'baseUrl', value: 'http://iris.test:52773' },
      { key: 'username', value: '_SYSTEM' },
      { key: 'password', value: '', type: 'secret' },
    ]);
    expect(c.auth.basic.map((b) => b.value)).toEqual(['{{username}}', '{{password}}']);
    expect(c.item.map((i) => i.name)).toEqual([
      'Namespaces',
      'Local databases',
      'GET /v1/{namespace}/doc/{docname}',
    ]);
    const folder = c.item[0] as { item: { request: { url: { raw: string; query?: unknown[] } } }[] };
    // An optional parameter without a value is present but disabled, so it shows in Postman.
    expect(folder.item[0].request.url.raw).toBe('{{baseUrl}}/api/admin/v2/namespaces');
    expect(folder.item[0].request.url.query).toEqual([
      { key: 'filter', value: '', description: 'A name filter', disabled: true },
    ]);
    const post = (c.item[1] as { item: { request: Record<string, unknown> }[] }).item[0].request;
    expect(post.method).toBe('POST');
    expect(post.header).toEqual([
      { key: 'Accept', value: 'application/json' },
      { key: 'Content-Type', value: 'application/json' },
    ]);
    expect(post.body).toEqual({
      mode: 'raw',
      raw: compact.body,
      options: { raw: { language: 'json' } },
    });
    expect(post.description).toBe('Compact a local database\nNeeds %Admin_Operate:U\nAnswers 202 Accepted');
    // Path parameters become Postman path variables.
    const item = c.item[2] as { request: { url: { path: string[]; variable?: unknown[] } } };
    expect(item.request.url.path).toEqual(['api', 'atelier', 'v1', ':namespace', 'doc', ':docname']);
    expect(item.request.url.variable).toEqual([
      { key: 'namespace', value: '' },
      { key: 'docname', value: '' },
    ]);
    // The password is never in the file.
    expect(JSON.stringify(c)).not.toMatch(/SYS"/);
  });

  it('writes a .http file with file variables, one block per request and encoded query values', () => {
    const text = httpFile(target, [list, compact]);
    expect(text).toContain('@baseUrl = http://iris.test:52773\n@username = _SYSTEM\n@password =\n');
    expect(text).toContain(
      '### GET /v2/namespaces · List namespaces\n# Namespaces\n# Needs %Admin_Manage:U\n',
    );
    expect(text).toContain('# Optional query parameters left out: filter\n');
    expect(text).toContain(
      'GET {{baseUrl}}/api/admin/v2/namespaces HTTP/1.1\nAccept: application/json\nAuthorization: Basic {{username}} {{password}}\n',
    );
    expect(text).toContain(
      'POST {{baseUrl}}/api/admin/v2/database-dir/compact?dir=%2Fusr%2Firissys%2Fmgr%2Fuser%2F&verbose=true HTTP/1.1\nAccept: application/json\nContent-Type: application/json\nAuthorization: Basic {{username}} {{password}}\n\n{\n  "TargetFreeSpace": 0\n}\n',
    );
    expect(text.endsWith('\n')).toBe(true);
  });

  it('writes a curl command that asks for the password and quotes the body', () => {
    expect(curlCommand(target, list)).toBe(
      "curl -u '_SYSTEM' \\\n  -H 'Accept: application/json' \\\n  'http://iris.test:52773/api/admin/v2/namespaces'",
    );
    const c = curlCommand(target, { ...compact, body: `{"Note":"it's"}` });
    expect(c).toContain(
      "-X POST \\\n  -H 'Content-Type: application/json' \\\n  --data-binary '{\"Note\":\"it'\\''s\"}'",
    );
    expect(c).toContain(
      "'http://iris.test:52773/api/admin/v2/database-dir/compact?dir=%2Fusr%2Firissys%2Fmgr%2Fuser%2F&verbose=true'",
    );
  });

  it('resolves a profile base URL against the page origin and names files', () => {
    expect(absoluteBaseUrl('', 'http://portal.test')).toBe('http://portal.test');
    expect(absoluteBaseUrl('/iris-b/', 'http://portal.test')).toBe('http://portal.test/iris-b');
    expect(absoluteBaseUrl('https://iris.lab:52773/', 'http://portal.test')).toBe('https://iris.lab:52773');
    expect(pathParamsOf('/v1/{namespace}/doc/{docname}')).toEqual(['namespace', 'docname']);
    expect(fileStem('/api/atelier')).toBe('api-atelier');
    expect(fileStem('SysAdmin APIs v2')).toBe('sysadmin-apis-v2');
    expect(fileStem('///')).toBe('requests');
  });
});
